name: Update data
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run script
        run: |
          echo ::set-output name=results::$(python update/update.py)
        id: run_script
      - name: what changed
        env:
          RESULTS: ${{ steps.run_script.outputs.results }}
        run: |
          echo ::set-output name=number::$(echo "$RESULTS" | jq ".number")
          echo ::set-output name=message::$(echo "$RESULTS" | jq ".message" | sed -e "s/\"//g")
        id: changed
      - name: log
        env:
          NUMBER: ${{ steps.changed.outputs.number }}
          MESSAGE: ${{ steps.changed.outputs.message }}
        run: |
          echo "results"
          echo "$NUMBER changes"
          echo "message: $MESSAGE"
      - name: commit
        env:
          NUMBER: ${{ steps.changed.outputs.number }}
          MESSAGE: ${{ steps.changed.outputs.message }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: steps.changed.outputs.number > 0 
        run: |
          git config --global user.email "covid19-bot@example.com"
          git config --global user.name "covid19-bot"
          git add -A
          git status
          git commit -m "[ci] $MESSAGE"
          git push -q "https://$GH_TOKEN@github.com/mauforonda/covid19-bolivia.git" master
          
        
        
